version: "3.8"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    command: mysqld --sql_mode="" # disable strict mode
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$MYSQL_ROOT_PASSWORD",
        ]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - mysql5_network
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8889:80
    env_file:
      - .env
    networks:
      - mysql5_network
networks:
  mysql5_network:
    driver: bridge
